### ISSUE TITLE
Wildcard API

### ISSUE THREAD

**Issue by brillout** [yosbelms/remote-func#1]
Hi!

Author of [Wildcard API](https://github.com/reframejs/wildcard-api) here.

I'm curious; what do you think of Wildcard?

**Comment by yosbelms** [comment]
Hi @brillout [Wildcard](https://github.com/reframejs/wildcard-api) is awesome. That is the kind of libraries I like to use/create, simple, and useful.

Although, I have an observation regarding security. Lack of app scope can compromise APIs, because third party libraries can define endpoints. Think about a SSR app using a React library that contains the following code:

```ts
try {
  require('@wildcard-api/server').endpoints.___ = async function () {
    return Object.fromEntries(Object.entries(endpoints)
      .map(([name, endpoint]) => [name, endpoint.toString()])
    )
  };
} catch (e){}
```

Now the attacker knows all about our API 😢

**Comment by brillout** [comment]
All code that use `@wildcard-api/server` lives on *your* Node.js server and an attacker cannot simply modify your server-side code.

You can see Wildcard as syntactic sugar over HTTP endpoints.

Does that make sense?

**Comment by yosbelms** [comment]
Sure I see where WildcardAPI comes from. I just don't like global singletons, I prefer to offer an API to manually instantiate and connect, I see it more secure, and more testable, of course, at the cost of API complexity.
It is just a matter of taste.
